import pandas as pd
import random
import openai
import argparse
from textwrap import dedent

"""
    Here the objective is to read the file data/csat_with_clusters.csv (generated by the baseline_topics.py), 
    sample some comments per cluster and ask the LLM to provide:
        1. A short name for the topic,
        2. A summary in bullet points,
        3. Some suggested actions.
"""


# -------------------------------------------------------------
# 1. Client Config 
# -------------------------------------------------------------


openai.api_key =  ""  

def ask_llm(prompt, model="gpt-4o-mini", max_tokens=500):
    """
    Send the prompt to the LLM and returns the reponse text.
    """
    response = openai.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        max_tokens=max_tokens,
        temperature=0.4,
    )
    return response.choices[0].message.content.strip()

# -------------------------------------------------------------
# 2. Main Function
# -------------------------------------------------------------
def summarize_clusters(csv_path, out_path, n_examples=15):
    df = pd.read_csv(csv_path)
    clusters = sorted(df["cluster"].dropna().unique())

    results = []

    for c in clusters:
        subset = df[df["cluster"] == c].dropna(subset=["commentaire"])
        sample = subset["commentaire"].sample(
            min(n_examples, len(subset)), random_state=42
        )

        prompt = dedent(f"""
        Tu es un analyste de la satisfaction client.
        On te donne un ensemble de verbatims clients (en français).
        Ton objectif est de :
        1. Donner un TITRE COURT (≤4 mots) au thème commun.
        2. Résumer en 3 points les idées principales.
        3. Suggérer 3 actions concrètes que l'entreprise pourrait entreprendre.

        Voici les {len(sample)} commentaires :
        {"; ".join(sample.tolist())}
        """)

        print(f"\nAnalyzing cluster {c} ({len(subset)} verbatims)...")
        summary = ask_llm(prompt)

        results.append({
            "cluster": c,
            "n_verbatims": len(subset),
            "sample_comments": "; ".join(sample.tolist()),
            "llm_summary": summary
        })

    res_df = pd.DataFrame(results)
    res_df.to_csv(out_path, index=False)
    print(f"Saved results in {out_path}")
    return res_df

# -------------------------------------------------------------
# 3. Direct Execution
# -------------------------------------------------------------
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--csv", default="data/csat_with_clusters.csv")
    parser.add_argument("--out", default="data/cluster_summaries.csv")
    parser.add_argument("--n", type=int, default=15)
    args = parser.parse_args()

    summarize_clusters(args.csv, args.out, args.n)
